version: "3.8"
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_container
    volumes:
      - ./mpay:/var/www
    working_dir: /var/www/public
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678@
      MYSQL_DATABASE: mpay
      MYSQL_USER: mpay
      MYSQL_PASSWORD: 12345678@
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "81:80"
    volumes:
      - ./mpay:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

volumes:
  mysql_data:
